kind: pipeline
type: docker
name: build_and_push
steps:
- name: install_dependencies
  image: node:16  # Replace with the appropriate Node.js version
  commands:
    - cd drone_deploy
    - npm install

- name: build
  image: node:16  # Replace with your build image
  commands:
    - cd drone_deploy
    - npm run build

- name: deploy-to-firebase
    image: node:16
    environment:
      FIREBASE_TOKEN: 1//09yis-h9DDMyPCgYIARAAGAkSNwF-L9Iryv2VpMnehBjVHUq-3WFomFDlWChMspbRvN7qUAifb2rpu89yN8wSyOWRG3gdoNLU7PU
      FIREBASE_PROJECT_ID: deploy-17f14
    commands:
      - firebase use --add $FIREBASE_PROJECT_ID
      - firebase deploy --token $FIREBASE_TOKEN